EXAMPLES = [
    {
        "id": "tomato-route",
        "label": "Tomatoes to the market",
        "tag": "BULK TRANSPORT",
        "description": "100 kg of ripe tomatoes. A 38-hour journey, with ventilation and crush protection.",
        "scenario": {
            "title": "Tomatoes to the market",
            "commodity": "tomato",
            "format": "bulk",
            "condition": "whole",
            "shipment_kg": 100,
            "maturity": "ripe",
            "rough_handling": True,
            "stages": [
                {
                    "name": "Pack & wait",
                    "hours": 2,
                    "temperature_c": 25,
                    "rh_percent": 65,
                },
                {
                    "name": "On the road",
                    "hours": 12,
                    "temperature_c": 25,
                    "rh_percent": 65,
                },
                {
                    "name": "At the destination",
                    "hours": 24,
                    "temperature_c": 20,
                    "rh_percent": 70,
                },
            ],
        },
    },
    {
        "id": "broccoli-cold",
        "label": "Broccoli, kept cool",
        "tag": "FRESH PRODUCE",
        "description": "A 500 g retail pack at 5 °C. Explore how respiration sets the gas-transfer target.",
        "scenario": {
            "title": "Broccoli, kept cool",
            "commodity": "broccoli",
            "format": "retail",
            "condition": "whole",
            "shipment_kg": 50,
            "pack_mass_kg": 0.5,
            "area_m2": 0.06,
            "stages": [
                {
                    "name": "Pack & wait",
                    "hours": 2,
                    "temperature_c": 5,
                    "rh_percent": 95,
                },
                {
                    "name": "On the road",
                    "hours": 12,
                    "temperature_c": 5,
                    "rh_percent": 95,
                },
                {
                    "name": "At the destination",
                    "hours": 24,
                    "temperature_c": 5,
                    "rh_percent": 95,
                },
            ],
        },
    },
    {
        "id": "peanut-barrier",
        "label": "A crisp, dry snack",
        "tag": "BARRIER BUDGET",
        "description": "A 30-day planning horizon with illustrative moisture and oxygen tolerances.",
        "scenario": {
            "title": "A crisp, dry snack",
            "commodity": "peanuts",
            "format": "retail",
            "condition": "dry",
            "shipment_kg": 20,
            "pack_mass_kg": 0.2,
            "area_m2": 0.06,
            "allowable_moisture_gain_g": 2,
            "oxygen_budget_ml": 12,
            "initial_oxygen_ml": 3,
            "budget_basis": "illustrative",
            "stages": [
                {
                    "name": "Pack & wait",
                    "hours": 2,
                    "temperature_c": 25,
                    "rh_percent": 65,
                },
                {
                    "name": "On the road",
                    "hours": 12,
                    "temperature_c": 25,
                    "rh_percent": 65,
                },
                {
                    "name": "At the destination",
                    "hours": 706,
                    "temperature_c": 25,
                    "rh_percent": 65,
                },
            ],
        },
    },
]
