import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check, Clock3, Leaf, Package, Route, Thermometer, Truck } from 'lucide-react'
import type { Catalog, Scenario, Stage } from './types'
import { ProduceArt } from './Artwork'
import { formatValue } from './api'

export function NumberField({label,value,onChange,unit,min=0,max,step='any',hint,required=false}: {label:string;value:number|null;onChange:(n:number|null)=>void;unit?:string;min?:number;max?:number;step?:string;hint?:string;required?:boolean}) {
  return <label className="field"><span>{label}{required && <span className="required"> *</span>}</span><div className="number-wrap"><input type="number" inputMode="decimal" value={value ?? ''} placeholder="Unknown" min={min} max={max} step={step} required={required} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/>{unit&&<span>{unit}</span>}</div>{hint&&<small>{hint}</small>}</label>
}

export function Planner({scenario:s,catalog,onChange,onEvaluate,busy,error,onBack}: {scenario:Scenario;catalog:Catalog;onChange:(s:Scenario)=>void;onEvaluate:()=>void;busy:boolean;error:string;onBack:()=>void}) {
  const [step,setStep]=useState(0),[localError,setLocalError]=useState('')
  const dry=['peanuts','chips'].includes(s.commodity),retail=s.format==='retail', hours=s.stages.reduce((a,b)=>a+b.hours,0)
  const update=(change:Partial<Scenario>)=>{setLocalError('');onChange({...s,...change})}
  const updateStage=(i:number,change:Partial<Stage>)=>update({stages:s.stages.map((st,j)=>j===i?{...st,...change}:st)})
  const choose=(id:Scenario['commodity'])=>{const f=catalog.foods.find(f=>f.id===id)!; const isDry=f.category==='dry';update({commodity:id,format:f.default_format,condition:isDry?'dry':'whole',maturity:'unknown',budget_basis:'unknown',allowable_moisture_gain_g:null,oxygen_budget_ml:null,initial_oxygen_ml:null})}
  const next=()=>{if(step===0&&(!s.shipment_kg||s.shipment_kg<=0)){setLocalError('Add the total shipment weight to continue.');return}if(step===1&&hours<=0){setLocalError('Add time to at least one journey stage.');return}setStep(v=>v+1);window.scrollTo({top:0,behavior:'instant'})}
  return <main className="page planner-page" id="main-content">
    <div className="page-topline"><button className="text-button" onClick={onBack}><ArrowLeft size={17}/>Workspace</button><span className="eyebrow">A PLAN BUILT AROUND YOUR FOOD</span></div>
    <div className="planner-layout"><section>
      <div className="steps" aria-label="Planning steps">{['Your food','The journey','Fine-tune'].map((label,i)=><button key={label} className={step===i?'current':step>i?'done':''} onClick={()=>{if(i<step)setStep(i);else if(i===step+1)next()}} aria-current={step===i?'step':undefined}><span>{step>i?<Check size={14}/>:String(i+1).padStart(2,'0')}</span>{label}</button>)}</div>
      <div className="section-heading"><span className="eyebrow">{['START WITH WHAT YOU KNOW','TIME IS PART OF THE PACKAGE','MAKE THE ASSUMPTIONS VISIBLE'][step]}</span><h1>{['What are you packing?','Every stop matters.','A little more context.'][step]}</h1><p>{['Tell us about the food. You can leave technical measurements unknown.','Include time before departure, on the road, and after arrival.','Review the planning values below. Missing evidence will appear clearly in your result.'][step]}</p></div>
      <form onSubmit={e=>{e.preventDefault();if(step<2)next();else onEvaluate()}}>
        {step===0&&<div className="form-body">
          <div className="food-options" role="group" aria-label="Commodity">{catalog.foods.map(f=><button type="button" key={f.id} className={`food-option ${s.commodity===f.id?'selected':''}`} onClick={()=>choose(f.id)}><span className={`food-dot ${f.id}`}><Leaf size={23}/></span><span><strong>{f.name}</strong><small>{f.category==='fresh'?'Fresh produce':'Dry food'}</small></span>{s.commodity===f.id&&<Check size={17}/>}</button>)}</div>
          <label className="field"><span>Give this plan a name</span><input value={s.title} maxLength={100} required onChange={e=>update({title:e.target.value})}/></label>
          <div className="field-grid"><NumberField label="Total shipment weight" value={s.shipment_kg||null} onChange={v=>update({shipment_kg:v??0})} unit="kg" min={0.001} max={1000000} required/><label className="field"><span>How will you pack it?</span><select value={s.format} onChange={e=>update({format:e.target.value as Scenario['format']})}><option value="bulk">Bulk transport / crates</option><option value="retail">Individual retail packs</option></select></label></div>
          {!dry&&<div className="field-grid"><label className="field"><span>Product condition</span><select value={s.condition} onChange={e=>update({condition:e.target.value as Scenario['condition']})}><option value="whole">Whole, uncut produce</option><option value="cut">Cut / processed produce</option></select></label>{s.commodity==='tomato'&&<label className="field"><span>Tomato maturity</span><select value={s.maturity} onChange={e=>update({maturity:e.target.value as Scenario['maturity']})}><option value="unknown">I'm not sure</option><option value="mature_green">Mature green</option><option value="ripe">Ripe</option></select></label>}</div>}
          {retail&&<div className="field-grid"><NumberField label="Weight in one pack" value={s.pack_mass_kg} onChange={v=>update({pack_mass_kg:v})} unit="kg" min={.001} max={1000} hint="500 g = 0.5 kg. This is different from the shipment weight."/><NumberField label="Exposed film area" value={s.area_m2} onChange={v=>update({area_m2:v})} unit="m²" min={.0001} max={100} hint="Count all effective film faces. 600 cm² = 0.06 m²."/></div>}
          <div className="inline-note"><Leaf size={19}/><p>Organic and conventional produce both need the right handling. Packaging choices follow the food's condition and journey.</p></div>
        </div>}
        {step===1&&<div className="form-body">
          <div className="timeline-ribbon">{s.stages.map((st,i)=><div key={i} style={{flex:Math.max(st.hours,Math.max(hours*.12,1))}}><span>{i===0?<Package size={18}/>:i===1?<Truck size={18}/>:<Leaf size={18}/>}</span><strong>{formatValue(st.hours)} h</strong><small>{st.name}</small></div>)}</div>
          <p className="form-note">The clock starts at packing. These stages add up once; time after arrival is not an extra shelf-life promise.</p>
          <div className="stage-list">{s.stages.map((st,i)=><fieldset key={i} className="stage"><legend><span>{String(i+1).padStart(2,'0')}</span>{st.name}</legend><div className="stage-fields"><NumberField label={`${st.name} duration`} value={st.hours} onChange={v=>updateStage(i,{hours:v??0})} unit="hours" max={8760} required/><NumberField label={`${st.name} temperature`} value={st.temperature_c} onChange={v=>updateStage(i,{temperature_c:v})} unit="°C" min={-40} max={60}/><NumberField label={`${st.name} humidity`} value={st.rh_percent} onChange={v=>updateStage(i,{rh_percent:v})} unit="% RH" max={100}/></div></fieldset>)}</div>
          {s.commodity==='broccoli'&&<div className="preset-row"><span>Explore reference conditions</span>{[0,5,10,15,20].map(t=><button type="button" key={t} onClick={()=>update({stages:s.stages.map(st=>({...st,temperature_c:t}))})}>All at {t} °C</button>)}<small>Only use a shortcut if it matches your real conditions, or to explore an example.</small></div>}
          <label className="check-field"><input type="checkbox" checked={s.rough_handling} onChange={e=>update({rough_handling:e.target.checked})}/><span><strong>Rough roads or repeated handling</strong><small>Include extra mechanical-protection checks.</small></span></label>
        </div>}
        {step===2&&<div className="form-body">
          <fieldset className="priority-options"><legend>What matters most for this plan?</legend>{[{v:'balanced',t:'A balanced starting point',d:'Consider protection and practical material choices.'},{v:'less_material',t:'Explore simpler materials',d:'Prioritize a simpler structure, subject to verified performance.'},{v:'protection',t:'Explore more protection',d:'Compare higher-barrier structures where the food needs them.'}].map(p=><label key={p.v} className={s.priority===p.v?'selected':''}><input type="radio" name="priority" value={p.v} checked={s.priority===p.v} onChange={()=>update({priority:p.v as Scenario['priority']})}/><span><strong>{p.t}</strong><small>{p.d}</small></span></label>)}</fieldset>
          {dry&&<div className="technical-inputs"><h3>Product tolerance budgets</h3><p>These should come from product testing. Leave them unknown if you do not have measurements.</p><label className="field"><span>Where do these values come from?</span><select value={s.budget_basis} onChange={e=>update({budget_basis:e.target.value as Scenario['budget_basis']})}><option value="unknown">I don't have test data yet</option><option value="illustrative">Illustrative values / learning example</option><option value="measured">My product measurements</option></select></label><div className="field-grid"><NumberField label="Allowable moisture gain" value={s.allowable_moisture_gain_g} onChange={v=>update({allowable_moisture_gain_g:v})} unit="g/pack" min={.0001} max={1000}/><NumberField label="Total oxygen exposure allowance" value={s.oxygen_budget_ml} onChange={v=>update({oxygen_budget_ml:v})} unit="mL/pack" min={.0001} max={100000}/><NumberField label="Initial oxygen in the pack" value={s.initial_oxygen_ml} onChange={v=>update({initial_oxygen_ml:v})} unit="mL/pack" max={100000} hint="Include headspace and dissolved oxygen on the same gas-volume basis."/></div></div>}
          {!dry&&retail&&<details className="technical-inputs"><summary>Advanced: gas-transfer assumptions</summary><p>These are screening targets, not a validated atmosphere recipe. RQ is assumed unless measured.</p><div className="field-grid"><NumberField label="Respiratory quotient (RQ)" value={s.rq} onChange={v=>update({rq:v??1})} min={.5} max={2}/><NumberField label="Target oxygen" value={s.target_o2_percent} onChange={v=>update({target_o2_percent:v??5})} unit="%" min={3} max={10}/><NumberField label="Target carbon dioxide" value={s.target_co2_percent} onChange={v=>update({target_co2_percent:v??8})} unit="%" min={5} max={10}/></div></details>}
          <div className="inline-note"><Check size={20}/><p>Your plan will include calculated requirements where evidence is available, candidate materials, and the checks still needed before use.</p></div>
        </div>}
        {(localError||error)&&<div className="error-banner" role="alert">{localError||error}</div>}
        <div className="form-actions">{step>0?<button type="button" className="text-button" onClick={()=>setStep(v=>v-1)}><ArrowLeft size={17}/>Back</button>:<small>Fields marked * are required.</small>}<button type="submit" className="button primary" disabled={busy}>{busy?'Calculating your plan…':step<2?'Continue':'Build my packaging plan'}{!busy&&<ArrowRight size={18}/>}</button></div>
      </form>
    </section><aside className="journey-summary"><div className="eyebrow">YOUR JOURNEY AT A GLANCE</div><ProduceArt kind={s.commodity} small/><h3>{catalog.foods.find(f=>f.id===s.commodity)?.name}</h3><div className="summary-line"><Package size={17}/><span>{s.shipment_kg?`${formatValue(s.shipment_kg)} kg shipment`:'Shipment weight needed'}</span></div><div className="summary-line"><Clock3 size={17}/><span>{formatValue(hours)} hours from packing</span></div><div className="summary-line"><Thermometer size={17}/><span>{hours===0?'Add your journey stages':s.stages.some(st=>st.hours>0&&st.temperature_c===null)?'Some temperatures unknown':`${Math.min(...s.stages.filter(st=>st.hours>0).map(st=>st.temperature_c??0))}–${Math.max(...s.stages.filter(st=>st.hours>0).map(st=>st.temperature_c??0))} °C across stages`}</span></div><div className="summary-divider"/><Route size={22}/><p>A better pack starts with the whole journey.</p><small>Reference data supports the calculation. The final package still needs supplier and product validation.</small></aside></div>
  </main>
}
